### PR TITLE
New changes plus buttons

### PR DESCRIPTION
**Pull request by LGgameLAB**
So I added a new loop for the pre-menu of your game and included a button class to work with. I tried to add some comments but hopefully you can figure this out and implement it on your own. I also put some of you refresh and rendering commands into functions so they could be reused and organized. It's a bit messy; just put it together.

### CODE REVIEW

**Comment by Muszteey12** [comment]
> So I added a new loop for the pre-menu of your game and included a button class to work with. I tried to add some comments but hopefully you can figure this out and implement it on your own. I also put some of you refresh and rendering commands into functions so they could be reused and organized. It's a bit messy; just put it together.

**Comment by Muszteey12** [comment]
Thanks so much for this, I really appreciate. I'm just seeing it actually. I'll try it as soon as I can and get back to you. Thanks so much

**Comment by Muszteey12** [comment]
Hello, i tried merging the code into one branch and running it but it didnt work...i tried integrating the button classes you added but im really lost here. Im new to Github as well so i dont even know if im going about this correctly...sorry for the stress. please help if you can, i just want the menu to show first once i launch the .py file and then the buttons can start the game, I reverted the merge i approved earlier as well..thanks

**Comment by LGgameLAB** [comment]
Hmm that's strange. Sorry it didn't work for you. I just re-downloaded my pull request and it appeared to be fine for me. I must note that everytime I wish to run it I have to comment out all the audio lines and audio importations (also I am running it with python 3.9.1 & pygame 2.0.1). There is a lot going on with the global and local scope so that always makes it hard to deal with. As for the buttons, I recommend maybe watching a tutorial on object oriented code as it is the best and neatest way to write code especially for games. The button class lets you create button objects that have properties and methods (functions) like rect, update, and image. You seem to be doing fine with Github btw.

In terms of going forward, I recommend talking to other redditors who seem happy to help you on your code and move forward with game development but if you put your error in here then we should get this program working in no time. And if you want some more of my help I can stick more comments in the code to help you implement your own stuff.

**Pull request merged**
